/**
 * Bundle the MCP App widgets into self-contained HTML.
 *
 * The host renders a widget in a sandboxed iframe whose default CSP is
 * `default-src 'none'`, so the HTML has to carry its own CSS and JS inline —
 * nothing can be fetched. And the Worker has no filesystem, so the finished
 * HTML cannot be read at runtime the way the MCP Apps tutorial does with
 * fs.readFile. Both constraints point the same way: bundle at build time and
 * emit the HTML as a TypeScript module the server imports.
 *
 * Output: src/apps/generated/widgets.ts — generated, do not edit.
 *
 * Run via `npm run build:apps`; `npm run build` does it first.
 */
import { build } from "esbuild";
import { readdir, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const UI_DIR = "src/apps/ui";
const OUT = "src/apps/generated/widgets.ts";
const SUFFIX = ".widget.ts";

/** Wrap a bundled script in the minimal page the host will render. */
function page(title, css, js) {
  return `<!doctype html>
<html lang="sv">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>${css}</style>
</head>
<body>
<p class="empty">Laddar…</p>
<script type="module">${js}</script>
</body>
</html>`;
}

const entries = (await readdir(UI_DIR)).filter((f) => f.endsWith(SUFFIX)).sort();
if (entries.length === 0) throw new Error(`no ${SUFFIX} files in ${UI_DIR}`);

// the shell's CSS is a plain exported string; pull it out of a tiny bundle so
// it lands in <style> rather than being injected by script at runtime
const cssBundle = await build({
  entryPoints: [path.join(UI_DIR, "shell.ts")],
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: "es2022"
});
const cssMatch = /CSS\s*=\s*`([\s\S]*?)`/.exec(cssBundle.outputFiles[0].text);
if (!cssMatch) throw new Error("could not extract CSS from shell.ts");
const css = cssMatch[1];

const widgets = {};
for (const file of entries) {
  const id = file.slice(0, -SUFFIX.length).replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
  const result = await build({
    entryPoints: [path.join(UI_DIR, file)],
    bundle: true,
    write: false,
    format: "esm",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none"
  });
  widgets[id] = page(`Fortnox — ${id}`, css, result.outputFiles[0].text);
  const kb = Math.round(widgets[id].length / 1024);
  console.log(`  ${id.padEnd(18)} ${String(kb).padStart(4)} KB`);
}

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(
  OUT,
  `// GENERATED by scripts/build-apps.mjs — do not edit.
//
// One self-contained HTML document per widget: inline CSS, inline bundled JS,
// no external requests. See the script for why this is generated rather than
// read from disk at runtime.

export const WIDGET_HTML = ${JSON.stringify(widgets, null, 2)} as const;

/** Widget ids, derived from the files in src/apps/ui/*.widget.ts. */
export type WidgetId = keyof typeof WIDGET_HTML;

export const WIDGET_IDS = Object.keys(WIDGET_HTML) as WidgetId[];
`,
  "utf-8"
);
console.log(`wrote ${OUT} (${entries.length} widgets)`);
